name: CI/CD for auth-service

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем репозиторий
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Устанавливаем JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3. Установка Python для pytest
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 4 Кэшируем Gradle-зависимости (ускоряет сборку)
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 5. Сборка и тестирование проекта
      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build and test with Gradle
        run: ./gradlew clean build --no-daemon

      # 6. Создание bootJar (сервисный .jar)
      - name: Build bootJar
        run: ./gradlew :service:bootJar

      # 7. Сохраняем JAR как артефакт
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: auth-service-jar
          path: service/build/libs/*.jar

      # 8. Запуск auth-service с профилем dev_h2
      - name: Run auth-service
        run: |
          nohup java -jar service/build/libs/service-1.0.0.jar --spring.profiles.active=dev_h2 &
          sleep 15
        env:
          SPRING_PROFILES_ACTIVE: dev_h2

      # 9. Установка зависимостей для тестов Python
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test/requirements.txt

      # 10. Запуск функциональных тестов
      - name: Run functional tests
        run: |
          cd test
          pytest -v --base-url http://localhost:8081

      # 11. Собираем и публикуем Docker-образ в Docker Hub
      - name: Build Docker image
        run: docker build -t auth-service:${{ github.sha }} .

      - name: Push Docker image to Docker Hub
        if: github.ref == 'refs/heads/main'
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker tag auth-service:${{ github.sha }} $DOCKER_USERNAME/auth-service:latest
          docker push $DOCKER_USERNAME/auth-service:latest
